name: FreeDNS Auto Login (URL Parameter Method)

# 设置触发条件
on:
  workflow_dispatch:
  # 每月 1 号凌晨 03:00 UTC 自动运行一次
  schedule:
    - cron: '0 3 1 * *' 

jobs:
  auto_login:
    runs-on: ubuntu-latest
    
    env:
      USERNAME: ${{ secrets.AFRAID_USERNAME }}
      PASSWORD: ${{ secrets.AFRAID_PASSWORD }}
      
    steps:
      - name: 🔐 使用 URL 参数尝试自动登录
        id: url_login
        run: |
          # --- 步骤 1: 定义常量和 URL ---
          # 注意：URL 经过 URL 编码 (URL Encoding)
          # "/subdomain/" 编码后为 L3N1YmRvbWFpbi8=
          # 这是 freedns.afraid.org 用于触发特定操作（如登录和跳转到子域名页）的格式。
          BASE_LOGIN_URL="https://freedns.afraid.org/zc.php?/step=2&from=L3N1YmRvbWFpbi8=&action=auth"
          
          # 构造完整的带凭证的 URL
          FULL_URL="${BASE_LOGIN_URL}&username=${USERNAME}&password=${PASSWORD}"
          
          echo "尝试访问 URL: ${BASE_LOGIN_URL}&username=...&password=..."
          
          # --- 步骤 2: 发送 HEAD 请求并检查重定向 ---
          # 模拟原脚本，发送一个 HEAD 请求 (-I)
          # 如果登录成功，服务器应该会重定向 (HTTP 302/303) 到控制面板。
          
          CURL_OUTPUT=$(curl -s -L -I --write-out "* HTTP_CODE: %{http_code}\n* REDIRECT_URL: %{redirect_url}\n* URL_EFFECTIVE: %{url_effective}\n" -o /dev/null "$FULL_URL")
          
          echo -e "\n--- cURL 检查结果 ---\n$CURL_OUTPUT"
          
          # 从输出中提取重定向 URL
          REDIRECT_URL=$(echo "$CURL_OUTPUT" | grep "REDIRECT_URL" | awk '{print $NF}')
          
          echo -e "Note: 如果 'REDIRECT_URL' 为空，则表示自动登录失败。"

          # --- 步骤 3: 验证结果 ---
          # 检查 REDIRECT_URL 是否包含登录后页面的特征 (例如：/subdomain/ 或 /sub/control/)
          if [[ "$REDIRECT_URL" == *"/subdomain/"* ]] || [[ "$REDIRECT_URL" == *"/sub/control/"* ]]; then
            echo "✅ URL 自动登录成功！重定向到控制面板。"
          else
            echo "::error:: 自动登录失败！未检测到有效的控制面板重定向链接。"
            echo "请检查用户名和密码是否正确，以及 freedns.afraid.org 是否仍支持此种登录方式。"
            exit 1
          fi

          # 由于这种方法通常也包含了“访问”账户的操作，可能已自动保持活跃。
          # 如果您需要明确延长休眠账户，请添加以下步骤：

          echo "登录会话有效。尝试延长账户期限..."
          DORMANT_EXTEND_URL="https://freedns.afraid.org/dormant/?action=extend"
          
          # 再次使用 URL 登录方式（携带凭证）来访问延长页面
          # 这种 URL 方式登录通常不会设置持续性的 Cookie，因此每次请求都需携带凭证。
          EXTEND_URL="${DORMANT_EXTEND_URL}&username=${USERNAME}&password=${PASSWORD}"
          
          EXTEND_RESPONSE=$(curl -s -L "$EXTEND_URL")

          if echo "$EXTEND_RESPONSE" | grep -q "Your account has been extended"; then
            echo "✅ 账户延长成功！"
          elif echo "$EXTEND_RESPONSE" | grep -q "You have no dormant domains"; then
            echo "✅ 账户目前没有休眠域名，任务完成。"
          else
            echo "⚠️ 延长操作结果不明确，请手动检查账户。"
          fi
